name: smapputil
dependencies:
- python=3.5.1
- pylint=1.5.4
- pip:
    - pysmap
    - psutil==4.1.0
    - sshtunnel==0.0.8.1 
    - python-crontab==2.0.1
    - pymongo==3.2.1
    - pip-autoremove==0.9.0
    - python-dateutil==2.4.2
    - six==1.10.0
    - wheel==0.29.0
    - argparse==1.4.0
    - tweepy==3.4.0
    - paramiko==1.16.0
    - envelopes==0.4
    - smappPy==0.1.31
    - elasticsearch==2.3.0
    - smappdragon==0.0.43